version: '3.1'
networks:
  frontend:
    driver: bridge

services:
  vertica:
    image: dataplatform/docker-verticadocker
    restart: always
    networks:
       - frontend
    ports:
      - 5433:5433
    volumes:
      - ./vertica_data:/home/dbadmin/docker